services:
  web:
    build:
      context: ./web
    environment:
      - FRAMEWORK=laravel  # o symfony, o none
    ports:
      - "80:80"
    volumes:
      - ./development:/var/www/html/demo 
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: "demo_db"
      MARIADB_USER: demo_user
      MARIADB_PASSWORD: demo_password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
